spring:
  datasource:
    driver-class-name: oracle.jdbc.driver.OracleDriver
    username: test
    password: test
    url: jdbc:oracle:thin:@47.93.249.9:1521:xe
  jpa:
    show-sql: true
  thymeleaf:
    cache: false
    suffix: .html
    mode: HTML5
    encoding: UTF-8
server:
  port: 8080

#公共配置与profiles选择无关 mapperLocations指的路径是src/main/resources
mybatis:
  typeAliasesPackage: com.xiuluo
  mapperLocations: classpath:mapper/*.xml